import tiktok1 from './assets/tiktok1.jpeg';
import tiktok2 from './assets/tiktok2.jpg';
import img1 from './assets/wmz_new.png';
import img2 from './assets/qiwi.png';
import img3 from './assets/capitalist.png';
import img4 from './assets/coinbase.png';
import img5 from './assets/usdt_full.png';

export const info = [
	{
		id: 1,
		img: tiktok1,
		title: 'Tiktok Ads (PrePay БЕЗ НДС) ПРЕДОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО ЕВРОПА/EU Mix',
		pageName: 'tiktok-eu',
		inStock: 13,
		geo: 'ЕВРОПА',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 1300,
	},
	{
		id: 2,
		img: tiktok1,
		title: 'Tiktok Ads (PrePay БЕЗ НДС) ПРЕДОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО ПОЛЬША/PL',
		pageName: 'tiktok-pl',
		inStock: 20,
		geo: 'ПОЛЬША',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	{
		id: 3,
		img: tiktok1,
		title: 'Tiktok Ads (PrePay БЕЗ НДС) ПРЕДОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО ИСПАНИЯ/ES',
		pageName: 'tiktok-es',
		inStock: 16,
		geo: 'ИСПАНИЯ',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	{
		id: 4,
		img: tiktok1,
		title: 'Tiktok Ads (PrePay БЕЗ НДС) ПРЕДОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО ПОРТУГАЛИЯ/PT',
		pageName: 'tiktok-pt',
		inStock: 18,
		geo: 'ПОРТУГАЛИЯ',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	{
		id: 5,
		img: tiktok1,
		title: 'Tiktok Ads (PrePay БЕЗ НДС) ПРЕДОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО АВСТРАЛИЯ/AU',
		pageName: 'tiktok-au',
		inStock: 18,
		geo: 'АВСТРАЛИЯ',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	{
		id: 6,
		img: tiktok1,
		title: 'Tiktok Ads (PrePay БЕЗ НДС) ПРЕДОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО КАНАДА/CA',
		pageName: 'tiktok-ca',
		inStock: 18,
		geo: 'КАНАДА',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	{
		id: 7,
		img: tiktok1,
		title: 'Tiktok Ads (PrePay БЕЗ НДС) ПРЕДОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО США/USA',
		pageName: 'tiktok-usa',
		inStock: 18,
		geo: 'США',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	{
		id: 8,
		img: tiktok1,
		title: 'Tiktok Ads (PrePay БЕЗ НДС) ПРЕДОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО БРАЗИЛИЯ/BR',
		pageName: 'tiktok-br',
		inStock: 18,
		geo: 'БРАЗИЛИЯ',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	{
		id: 9,
		img: tiktok1,
		title: 'Tiktok Ads (PrePay БЕЗ НДС) ПРЕДОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО ЮАР/ZA',
		pageName: 'tiktok-za',
		inStock: 18,
		geo: 'ЮАР',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},

	{
		id: 10,
		img: tiktok1,
		title: 'Tiktok Ads (PostPay БЕЗ НДС) ПОСТ ОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО ЕВРОПА/EU Mix',
		pageName: 'tiktok-eu',
		inStock: 18,
		geo: 'ЕВРОПА',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	{
		id: 11,
		img: tiktok1,
		title: 'Tiktok Ads (PostPay БЕЗ НДС) ПОСТ ОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО ПОЛЬША/PL',
		pageName: 'tiktok-pl',
		inStock: 18,
		geo: 'ПОЛЬША',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	{
		id: 12,
		img: tiktok1,
		title: 'Tiktok Ads (PostPay БЕЗ НДС) ПОСТ ОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО ИСПАНИЯ/ES',
		pageName: 'tiktok-es',
		inStock: 18,
		geo: 'ИСПАНИЯ',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	{
		id: 13,
		img: tiktok1,
		title: 'Tiktok Ads (PostPay БЕЗ НДС) ПОСТ ОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО ПОРТУГАЛИЯ/PT',
		pageName: 'tiktok-pt',
		inStock: 18,
		geo: 'ПОРТУГАЛИЯ',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	{
		id: 14,
		img: tiktok1,
		title: 'Tiktok Ads (PostPay БЕЗ НДС) ПОСТ ОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО АВСТРАЛИЯ/AU',
		pageName: 'tiktok-au',
		inStock: 18,
		geo: 'АВСТРАЛИЯ',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	{
		id: 15,
		img: tiktok1,
		title: 'Tiktok Ads (PostPay БЕЗ НДС) ПОСТ ОПЛАТА',
		text: 'Кабинеты для рекламы ГЕО КАНАДА/CA',
		pageName: 'tiktok-ca',
		inStock: 18,
		geo: 'КАНАДА',
		countries: [
			'Canada',
			'Egypt',
			'Japan',
			'Korea',
			'Kuwait',
			'Qatar',
			'Saudi Arabia',
			'Turkey',
			'United Arab Emirates',
			'United States',
		],
		price: 130,
	},
	// {
	//   id: 5,
	//   img: tiktok2,
	//   title: 'Tiktok Ads ▶ Кабинеты для рекламы',
	//   text: 'Открыто ГЕО ЕВРОПЫ (PrePay) /Tiktok Ads ▶ Advertising Accounts Open EUROPE',
	//   pageName: 'tiktok-prepay-europe',
	//   inStock: 24,
	//   geo: 'США',
	//   countries: [
	//     'Canada',
	//     'Egypt',
	//     'Japan',
	//     'Korea',
	//     'Kuwait',
	//     'Qatar',
	//     'Saudi Arabia',
	//     'Turkey',
	//     'United Arab Emirates',
	//     'United States',
	//   ],
	//   price: 130,
	// },
	// {
	//   id: 6,
	//   img: tiktok2,
	//   title: 'Tiktok Ads ▶ Кабинеты для рекламы',
	//   text: 'Открыто ГЕО КАНАДА (PrePay) /Tiktok Ads ▶ Advertising Accounts Open EUROPE',
	//   pageName: 'tiktok-prepay-can',
	//   inStock: 35,
	//   geo: 'Канада',
	//   countries: [
	//     'Canada',
	//     'Egypt',
	//     'Japan',
	//     'Korea',
	//     'Kuwait',
	//     'Qatar',
	//     'Saudi Arabia',
	//     'Turkey',
	//     'United Arab Emirates',
	//     'United States',
	//   ],
	//   price: 130,
	// },
	// {
	//   id: 7,
	//   img: tiktok2,
	//   title: 'Tiktok Ads ▶ Кабинеты для рекламы',
	//   text: 'Открыто ГЕО США (PrePay) /Tiktok Ads ▶ Advertising Accounts Open EUROPE',
	//   pageName: 'tiktok-prepay-usa',
	//   inStock: 34,
	//   geo: 'США',
	//   countries: [
	//     'Canada',
	//     'Egypt',
	//     'Japan',
	//     'Korea',
	//     'Kuwait',
	//     'Qatar',
	//     'Saudi Arabia',
	//     'Turkey',
	//     'United Arab Emirates',
	//     'United States',
	//   ],
	//   price: 130,
	// },
];

export const payments = [
	{
		id: 1,
		img: img1,
		link: '',
	},
	{
		id: 2,
		img: img2,
		link: '',
	},
	{
		id: 3,
		img: img3,
		link: '',
	},
	{
		id: 4,
		img: img4,
		link: '',
	},
	{
		id: 5,
		img: img5,
		link: '',
	},
];
