import tiktok1 from './assets/tiktok1.jpeg';
import tiktok2 from './assets/tiktok2.jpg';
import img1 from './assets/wmz_new.png';
import img2 from './assets/qiwi.png';
import img3 from './assets/capitalist.png';
import img4 from './assets/coinbase.png';
import img5 from './assets/usdt_full.png';

export const info = [
  {
    id: 1,
    img: tiktok1,
    title: 'Tiktok Ads (PostPay БЕЗ НДС) ПОСТ ОПЛАТА',
    text: 'Кабинеты для рекламы Открыто ГЕО ЕВРОПЫ/Tiktok Ads',
    pageName: 'tiktok-europe',
    inStock: 13,
    geo: 'США',
    countries: [
      'Canada',
      'Egypt',
      'Japan',
      'Korea',
      'Kuwait',
      'Qatar',
      'Saudi Arabia',
      'Turkey',
      'United Arab Emirates',
      'United States',
    ],
    price: 1300,
  },
  {
    id: 2,
    img: tiktok1,
    title: 'Tiktok Ads (PostPay БЕЗ НДС) ПОСТ ОПЛАТА',
    text: 'Кабинеты для рекламы Открыто ГЕО КАНАДА/Tiktok Ads',
    pageName: 'tiktok-can',
    inStock: 20,
    geo: 'Франция',
    countries: [
      'Canada',
      'Egypt',
      'Japan',
      'Korea',
      'Kuwait',
      'Qatar',
      'Saudi Arabia',
      'Turkey',
      'United Arab Emirates',
      'United States',
    ],
    price: 130,
  },
  {
    id: 3,
    img: tiktok1,
    title: 'Tiktok Ads (PostPay БЕЗ НДС) ПОСТ ОПЛАТА',
    text: 'Кабинеты для рекламы Открыто ГЕО США/Tiktok Ads',
    pageName: 'tiktok-usa',
    inStock: 16,
    geo: 'Австралия',
    countries: [
      'Canada',
      'Egypt',
      'Japan',
      'Korea',
      'Kuwait',
      'Qatar',
      'Saudi Arabia',
      'Turkey',
      'United Arab Emirates',
      'United States',
    ],
    price: 130,
  },
  {
    id: 4,
    img: tiktok1,
    title: 'Tiktok Ads (PostPay БЕЗ НДС) ПОСТ ОПЛАТА',
    text: 'Кабинеты для рекламы Открыто ГЕО АВСТРАЛИЯ/Tiktok Ads',
    pageName: 'tiktok-aus',
    inStock: 18,
    geo: 'Норвегия',
    countries: [
      'Canada',
      'Egypt',
      'Japan',
      'Korea',
      'Kuwait',
      'Qatar',
      'Saudi Arabia',
      'Turkey',
      'United Arab Emirates',
      'United States',
    ],
    price: 130,
  },
  {
    id: 5,
    img: tiktok2,
    title: 'Tiktok Ads ▶ Кабинеты для рекламы',
    text: 'Открыто ГЕО ЕВРОПЫ (PrePay) /Tiktok Ads ▶ Advertising Accounts Open EUROPE',
    pageName: 'tiktok-prepay-europe',
    inStock: 24,
    geo: 'США',
    countries: [
      'Canada',
      'Egypt',
      'Japan',
      'Korea',
      'Kuwait',
      'Qatar',
      'Saudi Arabia',
      'Turkey',
      'United Arab Emirates',
      'United States',
    ],
    price: 130,
  },
  {
    id: 6,
    img: tiktok2,
    title: 'Tiktok Ads ▶ Кабинеты для рекламы',
    text: 'Открыто ГЕО КАНАДА (PrePay) /Tiktok Ads ▶ Advertising Accounts Open EUROPE',
    pageName: 'tiktok-prepay-can',
    inStock: 35,
    geo: 'Канада',
    countries: [
      'Canada',
      'Egypt',
      'Japan',
      'Korea',
      'Kuwait',
      'Qatar',
      'Saudi Arabia',
      'Turkey',
      'United Arab Emirates',
      'United States',
    ],
    price: 130,
  },
  {
    id: 7,
    img: tiktok2,
    title: 'Tiktok Ads ▶ Кабинеты для рекламы',
    text: 'Открыто ГЕО США (PrePay) /Tiktok Ads ▶ Advertising Accounts Open EUROPE',
    pageName: 'tiktok-prepay-usa',
    inStock: 34,
    geo: 'США',
    countries: [
      'Canada',
      'Egypt',
      'Japan',
      'Korea',
      'Kuwait',
      'Qatar',
      'Saudi Arabia',
      'Turkey',
      'United Arab Emirates',
      'United States',
    ],
    price: 130,
  },
];

export const payments = [
  {
    id: 1,
    img: img1,
    link: '',
  },
  {
    id: 2,
    img: img2,
    link: '',
  },
  {
    id: 3,
    img: img3,
    link: '',
  },
  {
    id: 4,
    img: img4,
    link: '',
  },
  {
    id: 5,
    img: img5,
    link: '',
  },
];
